name: Hello World Action

# 🔹 Permite rodar manualmente no GitHub
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem
        run: echo "👋 Olá, Mundo! Hoje é $(date)"
