name: Agendamento toda meia noite contar a quantidade de arquivos

on:
  schedule:
    - cron: "0 3 * * *"  

jobs:
  contar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Contar arquivos HTML
        run: |
          export TZ="America/Sao_Paulo"
          count=$(find . -type f | wc -l)
          echo "Meia-noite! Total de arquivos: $count"
