name: agendamento toda meia noite contar a quantidade de arquivos

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:

jobs:
  contar-arquivos:
    runs-on: ubuntu-latest

    steps:
      - name: Checar-repositório
        uses: actions/checkout@v3

      - name: Contar-arquivos
        run: |
          export TZ="America/Sao_Paulo"
          hora=$(date +%H)
          if [ "$hora" -eq 0 ]; then
            total=$(find . -type f | wc -l)
            echo "Total de arquivos à meia-noite em: $total"
          else
            echo "Não é meia-noite ainda."
