name: Hello World
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mostrar data e hora local (Horário de Brasília)
        run: echo "🕒 Data e hora local: $(TZ='America/Sao_Paulo' date '+%d/%m/%Y %H:%M:%S')"
