name: Listar diret贸rio completo

on:
  workflow_dispatch:

jobs:
  listar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar c贸digo do reposit贸rio
        uses: actions/checkout@v4

      - name: Listar arquivos e pastas
        run: |
          echo "Arquivos e pastas no diret贸rio atual:"
          ls -la
